### ISSUE TITLE
🐛 [Samba NAS] 12.5.0-nas1 addon starts and stops immediately after last update

### ISSUE THREAD

**Issue by tkarsk** [dianlight/hassio-addons#517]
### Addon

SambaNAS

### Description

After the last update the add-on stops immediately after the start.

### Reproduction steps

```bash
1. Go to 'Settings > Addons > SambaNAS'
2. Click on 'Start'
3. Go to 'Log'
4. See error

Rebooted the whole HA, did not help.
```

### Addon Logs

```bash
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Samba NAS
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 12.5.0-nas1
 You are running the latest version of this add-on.
 System: Home Assistant OS 16.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2025.9.4
 Home Assistant Supervisor: 2025.09.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
[09:07:17] INFO: Protection Mode is false
[09:07:17] INFO: MoreDisk or Automount option found!
modprobe: module xfs not found in modules.dep
[09:07:17] WARNING: xfs module not available!
---------------------------------------------------
Supported fs: 	ext3	ext2	ext4	squashfs	vfat	msdos	iso9660	erofs	ntfs3	exfat	btrfs
---------------------------------------------------
[09:07:17] INFO: MediaLibrary option found!
---------------------------------------------------
[09:07:21] INFO: Available Disk Labels:
[09:07:21] INFO: 	HA-USB[ntfs]
---------------------------------------------------
[09:07:21] INFO: MoreDisks to mount:
	HA-USB
[09:07:21] INFO: Automount is Enabled!
---------------------------------------------------
[09:07:21] INFO: Checking Mounting disks for reserved names:
	HA-USB
---------------------------------------------------
---------------------------------------------------
[09:07:22] INFO: Mounting disks:
	HA-USB
---------------------------------------------------
[09:07:22] WARNING: Your HA-USB is ntfs. This is an EXPERIMENTAL support
[09:07:25] INFO: Mount HA-USB[ntfs] Success!
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
[09:07:25] INFO: Hostname: homeassistant
[09:07:25] INFO: Enabling S.M.A.R.T for /dev/sda
[09:07:25] INFO: Interfaces: enp1s0 
[09:07:25] INFO: Docker Interface: hassio 172.30.32.0/23
[09:07:26] INFO: Enabling S.M.A.R.T for /dev/sdb
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user homeassistant.
Added user _ha_mount_user_.
---------------------------------------------------
[09:07:26] INFO: Exposed Disks Summary:
---------------------------------------------------
s6-rc: info: service init-samba successfully started
s6-rc: info: service init-mqtt: starting
s6-rc: info: service wsdd: starting
s6-rc: info: service smbd: starting
s6-rc: info: service nmbd: starting
s6-rc: info: service avahi: starting
s6-rc: info: service wsdd successfully started
s6-rc: info: service smbd successfully started
s6-rc: info: service nmbd successfully started
s6-rc: info: service cifs-supervisor-mount: starting
s6-rc: info: service avahi successfully started
[09:07:26] INFO: Automount Shares...
[09:07:26] INFO: Starting the AVAHI for homeassistant...
Waiting for daemon ...
[09:07:26] INFO: MQTT support not enabled in config
s6-rc: info: service init-mqtt successfully started
smbd version 4.21.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2024
[09:07:26] INFO: Wait Samba Server to going up..(max 60s)
nmbd version 4.21.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2024
[09:07:26] INFO: Starting the WSDD daemon -i enp1s0  for WORKGROUP/homeassistant...
s6-rc: info: service init-smartd successfully started
/etc/s6-overlay/s6-rc.d/cifs-supervisor-mount/run: line 38: device: unbound variable
s6-rc: warning: unable to start service cifs-supervisor-mount: command exited 1
/run/s6/basedir/scripts/rc.init: warning: s6-rc failed to properly bring all the services up! Check your logs (in /run/uncaught-logs/current if you have in-container logging) for more information.
/run/s6/basedir/scripts/rc.init: fatal: stopping the container.
s6-rc: info: service init-smartd: stopping
s6-rc: info: service init-mqtt: stopping
s6-rc: info: service wsdd: stopping
s6-rc: info: service smbd: stopping
s6-rc: info: service nmbd: stopping
s6-rc: info: service hd-idle: stopping
s6-rc: info: service avahi: stopping
s6-rc: info: service init-smartd successfully stopped
s6-rc: info: service init-mqtt successfully stopped
terminate: Got SIGTERM: going down...
Got SIGTERM, quitting.
[09:07:27] INFO: avahi stopped
[09:07:27] INFO: hd-idle stopped
s6-rc: info: service hd-idle successfully stopped
s6-rc: info: service avahi successfully stopped
[09:07:27] INFO: wsdd stopped
s6-rc: info: service wsdd successfully stopped
[09:07:27] INFO: nmbd stopped
s6-rc: info: service nmbd successfully stopped
[09:07:27] INFO: smbd stopped
s6-rc: info: service smbd successfully stopped
s6-rc: info: service init-samba: stopping
s6-rc: info: service init-samba successfully stopped
s6-rc: info: service init-automount: stopping
[09:07:27] INFO: Unmount drivers:
/mnt/HA-USB
[09:07:27] INFO: Bye.
s6-rc: info: service init-automount successfully stopped
s6-rc: info: service legacy-cont-init: stopping
s6-rc: info: service legacy-cont-init successfully stopped
s6-rc: info: service fix-attrs: stopping
s6-rc: info: service base-addon-log-level: stopping
s6-rc: info: service fix-attrs successfully stopped
s6-rc: info: service base-addon-log-level successfully stopped
s6-rc: info: service base-addon-banner: stopping
s6-rc: info: service base-addon-banner successfully stopped
s6-rc: info: service s6rc-oneshot-runner: stopping
s6-rc: info: service s6rc-oneshot-runner successfully stopped
```

### Addon Config

```bash
workgroup: WORKGROUP
username: homeassistant
local_master: true
allow_hosts:
  - 192.168.1.0/24
automount: true
moredisks:
  - HA-USB
mountoptions:
  - nosuid
  - relatime
  - noexec
available_disks_log: true
medialibrary:
  enable: true
veto_files:
  - ._*
  - .DS_Store
  - Thumbs.db
  - icon?
  - .Trashes
compatibility_mode: false
recyle_bin_enabled: false
wsdd2: false
wsdd: true
mqtt_nexgen_entities: false
autodiscovery: {}
other_users: []
acl:
  - share: config
    disabled: true
  - share: addon_configs
    disabled: true
  - share: addons
    disabled: true
  - share: backup
    disabled: true
  - share: share
    disabled: true
  - share: ssl
    disabled: true
interfaces: []
password:
```

### Architecture

amd64

### OS

HaOS

**Comment by tkarsk** [comment]
Restored version 12.5.0-nas from backup, addon works again!

**Comment by dianlight** [comment]
Thanks for the report, I was able to replicate the error in my lab and I withdrew the release, the change in behavior does not seem directly related to the application changes but rather to the upgrade of the Alpine image used and therefore not easy to resolve.

**Comment by dianlight** [comment]
The beta version 12.5.0-nas2.beta145 should fix it.
I appreciate a feedback

L

**Comment by petebanham** [comment]
Unfortunately it has not fixed it for me. I installed the Beta, stopped the  original version, copied the ymal config over, started the beta and restart HA and HAOS for good measure :-) 

log below:
```
s6-rc: info: service s6rc-oneshot-runner: starting
s6-rc: info: service s6rc-oneshot-runner successfully started
s6-rc: info: service base-addon-banner: starting
-----------------------------------------------------------
 Add-on: Samba NAS-β
 Expose Home Assistant disc with SMB/CIFS
-----------------------------------------------------------
 Add-on version: 12.5.0-nas2.beta145
 You are running the latest version of this add-on.
 System: Home Assistant OS 16.2  (amd64 / generic-x86-64)
 Home Assistant Core: 2025.9.4
 Home Assistant Supervisor: 2025.09.3
-----------------------------------------------------------
 Please, share the above information when looking for help
 or support in, e.g., GitHub, forums or the Discord chat.
-----------------------------------------------------------
s6-rc: info: service base-addon-banner successfully started
s6-rc: info: service fix-attrs: starting
s6-rc: info: service base-addon-log-level: starting
s6-rc: info: service fix-attrs successfully started
s6-rc: info: service base-addon-log-level successfully started
s6-rc: info: service legacy-cont-init: starting
s6-rc: info: service legacy-cont-init successfully started
s6-rc: info: service init-automount: starting
[11:26:50] INFO: Protection Mode is false
[11:26:50] INFO: MoreDisk or Automount option found!
modprobe: module xfs not found in modules.dep
[11:26:51] WARNING: xfs module not available!
---------------------------------------------------
Supported fs: 	ext3	ext2	ext4	squashfs	vfat	msdos	iso9660	erofs	ntfs3	exfat	btrfs
---------------------------------------------------
[11:26:51] INFO: MediaLibrary disabled in config. Disk are mounted only for this addon!
---------------------------------------------------
[11:26:52] INFO: Available Disk Labels:
[11:26:52] INFO: 	Video[ext4]
[11:26:52] INFO: 	Secure[ext4]
---------------------------------------------------
[11:26:52] INFO: No MoreDisks to mount
[11:26:52] INFO: Automount is Enabled!
---------------------------------------------------
[11:26:52] INFO: Checking Mounting disks for reserved names:
	Secure
	Video
---------------------------------------------------
---------------------------------------------------
[11:26:52] INFO: Mounting disks:
	Secure
	Video
---------------------------------------------------
[11:26:52] INFO: Mount Secure[ext4] Success!
[11:26:52] INFO: Mount Video[ext4] Success!
s6-rc: info: service init-automount successfully started
s6-rc: info: service init-smartd: starting
s6-rc: info: service init-samba: starting
s6-rc: info: service hd-idle: starting
s6-rc: info: service hd-idle successfully started
[11:26:52] INFO: Hostname: homeassistant
[11:26:52] INFO: Interfaces: enp1s0 wlo1 enp2s0 
[11:26:52] INFO: Enabling S.M.A.R.T for /dev/nvme0
[11:26:52] INFO: Docker Interface: hassio 172.30.32.0/23
[11:26:52] INFO: Enabling S.M.A.R.T for /dev/nvme1
s6-rc: info: service init-smartd successfully started
tdbsam_open: Converting version 0.0 database to version 4.0.
tdbsam_convert_backup: updated /var/lib/samba/private/passdb.tdb file.
Added user share.
Added user secureuser.
---------------------------------------------------
[11:26:52] INFO: Exposed Disks Summary:
[CONFIG]                path = /homeassistant # TM:false US:secureuser #
[CONFIG]                path = /homeassistant # TM:false US:secureuser #
[ADDONS]                path = /addons # TM:false US:secureuser #
[ADDONS]                path = /addons # TM:false US:secureuser #
[SSL]                   path = /ssl # TM:false US:secureuser #
[SSL]                   path = /ssl # TM:false US:secureuser #
[SHARE]                 path = /share # TM:false US:secureuser #
[SHARE]                 path = /share # TM:false US:secureuser #
[BACKUP]                path = /backup # TM:false US:secureuser #
[BACKUP]                path = /backup # TM:false US:secureuser #
[MEDIA]                 path = /media # TM:false US:secureuser #
[MEDIA]                 path = /media # TM:false US:secureuser #
[ADDON_CONFIGS]         path = /addon_configs # TM:false US:secureuser #
[ADDON_CONFIGS]         path = /addon_configs # TM:false US:secureuser #
[SECURE]                path = /mnt/Secure # TM:true US:secureuser #
[SECURE]                path = /mnt/Secure # TM:true US:secureuser #
[VIDEO]                 path = /mnt/Video # TM:true US:secureuser #
[VIDEO]                 path = /mnt/Video # TM:true US:secureuser #
---------------------------------------------------
s6-rc: info: service init-samba successfully started
s6-rc: info: service init-mqtt: starting
s6-rc: info: service wsdd: starting
s6-rc: info: service smbd: starting
s6-rc: info: service nmbd: starting
s6-rc: info: service avahi: starting
s6-rc: info: service nmbd successfully started
s6-rc: info: service smbd successfully started
s6-rc: info: service wsdd successfully started
s6-rc: info: service cifs-supervisor-mount: starting
s6-rc: info: service avahi successfully started
s6-rc: info: service cifs-supervisor-mount successfully started
[11:26:52] INFO: Starting the AVAHI for homeassistant...
[11:26:52] INFO: MQTT support not enabled in config
s6-rc: info: service init-mqtt successfully started
s6-rc: info: service mqtt-disk-handler: starting
s6-rc: info: service mqtt-disk-handler successfully started
s6-rc: info: service mqtt-handler: starting
Waiting for daemon ...
s6-rc: info: service mqtt-handler successfully started
s6-rc: info: service legacy-services: starting
[11:26:52] INFO: Starting the WSDD daemon -i enp1s0 -i wlo1 -i enp2s0  for WORKGROUP/homeassistant...
s6-rc: info: service legacy-services successfully started
2025-10-03 11:26:53,041:wsdd INFO(pid 504): using pre-defined UUID 86895232-590b-32f5-9b6a-9f2668def604
2025-10-03 11:26:53,042:wsdd INFO(pid 504): joined multicast group 239.255.255.250 on 192.168.5.7%enp2s0
2025-10-03 11:26:53,044:wsdd INFO(pid 504): scheduling Hello message via enp2s0 to 239.255.255.250%enp2s0
2025-10-03 11:26:53,096:wsdd INFO(pid 504): joined multicast group [ff02::c] on fe80::1ce0:be3f:cfbd:123f%enp2s0
2025-10-03 11:26:53,097:wsdd INFO(pid 504): scheduling Hello message via enp2s0 to ff02::c%enp2s0
smbd version 4.21.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2024
nmbd version 4.21.4 started.
Copyright Andrew Tridgell and the Samba Team 1992-2024
become_local_master_stage2: *****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 192.168.5.7
*****
become_local_master_stage2: *****
Samba name server HOMEASSISTANT is now a local master browser for workgroup WORKGROUP on subnet 172.30.32.1
*****
2025-10-03 11:31:45,914:wsdd INFO(pid 504): [fe80::f011:acb4:414f:bb2b]:57021(enp2s0) - - "Resolve urn:uuid:a3acbdc3-577f-44f2-be9e-46e2dc5b024a UDP" - -
2025-10-03 11:33:22,422:wsdd INFO(pid 504): [fe80::f493:f534:7e5f:3f1b]:56083(enp2s0) - - "Resolve urn:uuid:7be4eeb8-c0ff-4407-a15e-c3acf67c066b UDP" - -
token_contains_name: _ha_mount_user_ is a UNKNOWN, expected a user
token_contains_name: _ha_mount_user_ is a UNKNOWN, expected a user
token_contains_name: _ha_mount_user_ is a UNKNOWN, expected a user
token_contains_name: _ha_mount_user_ is a UNKNOWN, expected a user
create_connection_session_info: user 'share' (from session setup) not permitted to access this share (VIDEO)
make_connection_snum: create_connection_session_info failed: NT_STATUS_ACCESS_DENIED
token_contains_name: _ha_mount_user_ is a UNKNOWN, expected a user
create_connection_session_info: user 'share' (from session setup) not permitted to access this share (VIDEO)
make_connection_snum: create_connection_session_info failed: NT_STATUS_ACCESS_DENIED
```

**Comment by dianlight** [comment]
The beta version 12.5.0-nas2.beta146 has another fix on duplicate and more check on users.
I'm not sure that fix all problem because I can't reproduce the user problem. I appreciate a feedback

L

**Comment by petebanham** [comment]
I am out today but will give it go tomorrow. Thanks for your help.
